### ISSUE TITLE
New Maintainer

### ISSUE THREAD

**Issue by mikz** [capistrano/github#7]
Hi folks. I did a total rewrite of this library as it does not work at all.
We are using it in production for quite a lot of time and it works great.
See the PR: #8 

If you decide to merge it, I could set up as a maintainer of this project. 
Suggested by @elia in https://github.com/3scale/capistrano-github/pull/1#issuecomment-147706309

/cc @capistrano

**Comment by elia** [comment]
here's the usual :+1:

**Comment by hkdobrev** [comment]
@kirs Would you be willing to pass this on to a more active maintainer? Many thanks!

**Comment by kirs** [comment]
Sure. @mikz are you still willing to be a maintainer?

**Comment by kirs** [comment]
I'm also up to merging the PR and releasing new version of the gem myself. I was never pinged about this issue :neutral_face:

**Comment by mikz** [comment]
We are still actively using our fork. So I guess why not.  Not really planning new features because it just works, but happy to review and merge stuff if needed. 

31. 8. 2017 v 14:49, Kir Shatrov <notifications@github.com>:

**Comment by will-in-wi** [comment]
Closing this per https://github.com/capistrano/github/issues/9 in favor of https://github.com/3scale/capistrano-github. Future issues should be sent there.
