### ISSUE TITLE
delete this repo

### ISSUE THREAD

**Issue by jrochkind** [capistrano/github#9]
It hasn't been touched in ~3 years, and reportedly does not work with current dependencies. 

There is already a reportedly working fork at https://github.com/3scale/capistrano-github.  (which at least started from 3-year-old PR here which has no maintainer comments still). 

This repo should be deleted, so it doesn't mislead people who find it on google or github browser, and were really looking for the working fork.

**Comment by will-in-wi** [comment]
This makes sense to me, or at least a big notice at the top of the README pointing to the other repo. @mattbrictson @leehambley, any problems with my doing this?

**Comment by mattbrictson** [comment]
I agree we should add big message to the top of the README. Then we can mark this repo as Archived in the settings, which will make it read-only (issues/PRs can no longer be submitted).

**Comment by will-in-wi** [comment]
I've added the note. I'll mark as archived once I close existing issues and PRs.

**Comment by will-in-wi** [comment]
Other issues closed. Closing this one too, before archiving.
